version: "3.7"

services:

  api:
    build: .
    env_file:
      - local.env
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    env_file:
      - local.env

  redis:
    image: redis:6.2.4
